In [11]:
import torch
from torch import nn

## Linear

`nn.Linear(in_features, out_features)`: transforming dim(input_features) -> dim(out_features).

In [12]:
x = torch.randn(32, 100)
print(x, x.shape)

model = nn.Linear(100, 64*7*7) # nn.Linear: transforming dim(input_features) -> dim(out_features).
                               # E.g., from 100 dims -> 3136 dims
print(model(x), model(x).shape)

tensor([[-0.6485, -1.5237, -1.7439,  ...,  0.7603,  0.4626,  0.0316],
        [-0.4804, -2.1709,  0.7037,  ...,  2.1281, -1.2163, -0.8409],
        [-0.5072,  1.4991,  0.6176,  ...,  0.3955, -0.0602,  1.1866],
        ...,
        [-0.7686, -0.1500,  0.0652,  ...,  1.9597, -2.1393,  1.9549],
        [ 0.4637, -0.5647, -0.0551,  ..., -1.2601, -1.0934,  1.4556],
        [-0.0666, -0.3283, -0.0686,  ...,  1.0778, -0.6803,  0.6254]]) torch.Size([32, 100])
tensor([[-0.0371,  0.0666, -0.6927,  ...,  0.2740,  0.8559, -0.4376],
        [-0.4765,  0.4202, -0.7402,  ...,  0.0371, -0.6755,  0.1372],
        [-0.1077,  0.0965, -0.1991,  ..., -0.5920, -1.2852, -0.0286],
        ...,
        [ 1.5961,  0.3870, -1.2736,  ...,  0.6966,  0.8073,  1.0199],
        [ 0.0652, -0.0763, -0.0072,  ...,  0.0217,  0.2853, -0.0903],
        [ 0.8504, -0.4821, -0.0581,  ...,  0.0627, -1.0705, -0.3913]],
       grad_fn=<AddmmBackward0>) torch.Size([32, 3136])


In [13]:
x = model(x)
x.view(-1, 64, 7, 7)

tensor([[[[-3.7065e-02,  6.6583e-02, -6.9271e-01,  ...,  3.6429e-01,
           -7.9157e-01, -5.2238e-01],
          [-1.3761e-01,  3.1346e-02,  8.0390e-01,  ..., -1.1299e+00,
            3.4744e-01,  4.6691e-01],
          [-6.2500e-02,  3.2867e-01, -6.0202e-01,  ..., -5.1123e-01,
           -1.6879e-01,  1.7582e-01],
          ...,
          [ 7.0131e-01, -8.1904e-01,  2.3755e-01,  ...,  2.0047e-01,
            1.2952e-01, -2.7388e-01],
          [ 8.0304e-01, -2.6736e-01,  6.6207e-02,  ..., -5.4163e-01,
            4.2889e-01, -1.4574e-01],
          [-7.1527e-01,  1.3416e-01,  7.4565e-01,  ...,  8.3317e-02,
           -4.8955e-01,  1.2421e-01]],

         [[-3.5579e-01,  5.0385e-01, -4.2658e-01,  ..., -7.0159e-01,
            3.3506e-01, -1.2738e-01],
          [-3.4986e-01, -7.7847e-02, -3.3935e-02,  ...,  5.6411e-02,
            1.1990e+00,  4.2712e-01],
          [ 1.1360e+00,  1.7863e-01, -1.5218e-01,  ...,  7.2523e-02,
           -3.4506e-01, -6.6100e-01],
          ...,
     

In [15]:
x.shape, x.view(-1, 64, 7, 7).shape

(torch.Size([32, 3136]), torch.Size([32, 64, 7, 7]))

## ConvTranspose2d

nn.ConvTranspose2d(64, 64, kernel_size = 3, stride = 2, padding = 1, output_padding = 1)
nn.ConvTranspose2d(in_channels, out_channels, kernel_size, stride, padding)

In [23]:
x = torch.randn(32, 64, 7, 7)

model = nn.ConvTranspose2d(64, 64, kernel_size=3, stride=2, padding=1, output_padding=1)

In [25]:
x, x.shape

(tensor([[[[-6.6884e-01,  5.6907e-01,  1.2798e+00,  ..., -1.0479e+00,
            -9.2404e-02, -5.7299e-01],
           [-1.3565e+00, -2.9472e-01,  1.3217e+00,  ...,  1.5771e-02,
            -3.2931e-01,  3.1191e-03],
           [ 1.9808e-01,  1.1044e+00,  6.5102e-01,  ...,  1.0808e-01,
            -1.0777e+00,  5.4921e-01],
           ...,
           [-5.6734e-01, -1.9220e+00,  1.3258e+00,  ..., -9.2007e-01,
            -1.0588e+00,  2.9861e-01],
           [-5.6301e-02, -8.3134e-01,  5.8276e-01,  ...,  6.8812e-01,
            -1.2457e+00,  2.1157e-01],
           [ 4.6277e-01,  1.5483e+00, -1.1181e+00,  ...,  6.2732e-02,
            -7.8691e-01,  4.4574e-02]],
 
          [[-8.0889e-01, -1.2841e+00,  1.0210e-01,  ..., -7.1191e-01,
            -1.5910e+00,  9.3978e-01],
           [-1.5464e+00,  1.6031e+00,  1.1701e+00,  ...,  6.6492e-01,
            -4.4766e-01, -5.6711e-01],
           [-1.2898e+00,  1.0257e+00,  7.9977e-01,  ...,  1.0278e-01,
            -1.2513e-01,  7.2850e-01],


In [26]:
model(x), model(x).shape

(tensor([[[[ 4.1233e-03, -1.9502e-01,  8.0007e-02,  ...,  8.0944e-03,
             4.6150e-02, -3.8192e-02],
           [ 3.6549e-01, -5.8165e-01, -2.6685e-01,  ...,  7.3972e-02,
             2.0183e-01, -7.0852e-02],
           [-2.5198e-01,  3.8561e-02,  6.6213e-02,  ...,  2.7872e-02,
            -2.3121e-01,  4.5277e-02],
           ...,
           [ 4.6208e-02,  1.7165e-01, -1.6185e-01,  ..., -2.1496e-01,
             8.7910e-03, -4.5728e-01],
           [-4.0963e-02, -3.9050e-01,  3.8136e-02,  ...,  1.5446e-02,
            -2.4541e-01,  1.1460e-02],
           [ 1.9400e-01, -1.6418e-01, -3.4173e-01,  ...,  1.8336e-01,
             2.4633e-01,  5.6329e-02]],
 
          [[-1.8620e-01, -4.8024e-01, -8.0599e-05,  ..., -2.3705e-01,
            -3.2778e-01, -8.7922e-02],
           [ 3.5780e-01,  3.3046e-01,  1.0621e-01,  ..., -5.4741e-01,
            -1.8139e-01, -6.0446e-02],
           [-3.0074e-02, -7.3831e-02, -1.1387e-01,  ..., -3.3916e-01,
             1.3572e-02,  2.7715e-01],
